crdb/crdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls'))
]

crdb/search/urls.py
from django.conf.urls import url

from . import views

app_name = 'index'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<cr_id>[0-9]+)', views.detail, name='detail'),
    url(r'^download/$', views.download, name='download') # how to send current search result to function??
]

crdb/search_2/urls.py
from django.conf.urls import url

from . import views

app_name = 'search'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.home, name='index'),
]

crdb/search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class chromatin_regulator(models.Model):
    ensembl_id = models.CharField(max_length=50)
    gene_symbol = models.CharField(max_length=10)
    function = models.CharField(max_length=50)
    Description = models.CharField(max_length=100)
    genecards_link = models.CharField(max_length=1000)

    def __str__(self):
        return self.gene_symbol

crdb/search_2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class chromatin_regulators(models.Model):
	ensembl_id = models.CharField(max_length=1000)

crdb/search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import chromatin_regulator

# Create your views here.
def index(request):
    cr_result = chromatin_regulator.objects.all()
    context = {'result': cr_result}
    return render(request, "search/index.html",context)

def detail(request, cr_id):
    return HttpResponse("You are at DETAILS")

def download(request):
    return HttpResponse("You are at DOWNLOAD")

crdb/search_2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

def home(request):
    return render(request, "home.html")

crdb/search/templates/base.html
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <a class="navbar-brand" href="#">CRDB</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search:index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search:result' %}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search:download' %}">Download</a>
          </li>
        </ul>
    </nav>
    {% block content %}
    {% endblock%}
  </body>


</html>

crdb/search/templates/download.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <h2>Basic Table</h2>
  <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
  <table class="table">
    <thead>
      <tr>
        <th>Ensembl id</th>
        <th>Gene Symbol</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cr%}
        <tr>
          <td> {{item.ensembl_id}} </td>
          <td> {{item.gene_symbol}} </td>
        </tr>
      {% endfor%}
    </tbody>
</table>
</div>
{% endblock%}

crdb/search/templates/home.html
{% extends 'base.html' %}

{% block content %}

  <h2> Welcome to CRDB! </h2>

  <p> Some descriptions... </p>

{% endblock%}

crdb/search/templates/result.html
{% extends 'base.html' %}

{% block content %}

  <p> Loading results... </p>

{% endblock%}

crdb/search_2/templates/base.html
<html>
  <head>
  </head>

  <body>
    <ul>
      <li> <a href="{% url index %}"> home </a></li>
    </ul>

    {% block content %}
    {% end block%}
  </body>


</html>

crdb/search_2/templates/home.html
{% extends base.html %}

{% block content %}

  <h2> Welcome to CRDB! </h2>

{% end block%}